### ISSUE TITLE
Can't encounter Gastly in Lost Tower

### ISSUE THREAD

**Issue by nekmao33** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#14] opened 2024-11-01 18:53 UTC
My character is in the Lost Tower at the good spot. But even with the 700 fast spins, a Gastly didn't appear. (I try crank up the number up to 1400 fast spins, without success)
The team is actually :
- Haunter, lvl 25
- Eevee, lvl 32
- Lixy, lvl 10
- Infernape, lvl 39
<img width="256" alt="2024-11-01_19h52_48" src="https://github.com/user-attachments/assets/75ffbd7d-adbe-4a55-952c-4c7335b5d5da">
<img width="256" alt="2024-11-01_19h53_24" src="https://github.com/user-attachments/assets/25098103-d190-47ec-b3d9-e612df8a147b">

**Comment by KeeyanGhoreshi** [comment] 2024-11-01 19:11
that's because your team is somehow missing togetic and roselia in the party, and eevee is meant to be level 36.  There is likely something going wrong in between catching roselia and arriving at the lost tower.  You aren't seeing a gastly since togetic is meant to be the party leader at level 20, which is the max level it will spawn at.

**Comment by KeeyanGhoreshi** [comment] 2024-11-01 19:14
If you're able to share your savestate files, I could take a closer look and try to figure out what went wrong.

**Comment by nekmao33** [comment] 2024-11-01 19:15
From which savestate file do you want ?

**Comment by nekmao33** [comment] 2024-11-01 20:20
I made a Google Drive link with all the savestate files from catch Roselia to before catching Gastly.
Here's the link : https://drive.google.com/drive/folders/1MXC8x1-0pQKiUjXWmIuoozlPiOCLqiHk?usp=sharing
P.S. : I think I delete the 16th save by accident...

**Comment by KeeyanGhoreshi** [comment] 2024-11-01 20:34
Trying to load your save states causes my emulator to load the first frame, and then freeze before crashing lol.  Even still, I actually am pretty sure I know what the problem is.  Your before eevee and after eevee training states are both in the menu talking to the daycare lady, which means you get stuck in that dialogue for some reason.  

This is definitely the source of the problem, you don't do the daycare training for eevee, then somehow the inputs work out such that you still retrieve eevee (or maybe never even put them in?), and put togetic into the PC instead of the Valley Windworks mon.

I'm also pretty certain why this happens.  It is most likely due to the timing of the inputs when chatting with the daycare lady.  Given that there's no randomness in this part of the sequence, it's actually probably related to the game language being french (I think?), it might take longer for a text box to finish and there aren't enough B inputs to align it like is usually done for talking with NPCs. 

This is actually a pretty simple fix, but before I do that, I'd like to confirm my suspicions.  If you're able to load the save state 13b-Synchronized and start from there, you can watch it until it reaches the daycare lady and see what happens that causes it to get stuck talking to the lady.  Or if we can figure out how to get your save states to work on my emulator, I can check myself.  I think it might be related to the version of the ROM.

**Comment by nekmao33** [comment] 2024-11-02 10:41
I can give you my version of the ROM (in French) and adapt the code accordingly.
I've already done it 4 times due to speech text.
I've updated the Google Drive folder to include my Pokémon Platinum ROM.

**Comment by KeeyanGhoreshi** [comment] 2024-11-02 16:20
yeah, after checking the state & your rom this is the issue, in french the text box when talking to the daycare lady takes two boxes, which means it needs an additional input to get to the correct menu.  "I'm the Day-Care Lady. We can raise Pokemon for you." versus  "Je suis l'Hotesse de la Pension. Nous pouvons elever des Pokemon..." then after an input "...pour toi".

Unfortunately, because this is a text box that leads into a menu that consumes A/B inputs, there's not really a catch all fix for this that will last for the whole run.  The sequence is made for the english versions of the text boxes, so if it takes 2 inputs instead of 1 to get through the daycare lady's dialogue, this will not be accounted for.

In this specific instance, the change you need to make is here:
https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/4.lua#L1132

You need an additional ```{'press_a', 1},
    {'w', 180},``` right there to get it to correctly talk to the daycare lady. 

This will probably happen every single time it tries to go to the daycare, since the opening text box will always be 1 A input off.  So you will have to add this extra A input in all these places as well.  Here's all the places I could find that will probably need this extra A input:

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/4.lua#L1469

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/4.lua#L2025

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/4.lua#L4400

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/5.lua#L1055

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/7.lua#L642

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/7.lua#L1129

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/7.lua#L2786

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/7.lua#L4097

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/8.lua#L2254

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/9.lua#L837

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/9.lua#L915

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/9.lua#L963

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/0dfea10872bed18ce9fb475615a8435c749126b3/commands/9.lua#L1007

**Comment by nekmao33** [comment] 2024-11-03 00:22
It seems to have solved the problem, thanks !
Just after leaving the ruins (22nd save), we're supposed to beat Ty and Sue. Inputs can't beat them.
Does it still have something to do with my ROM, or is it something else entirely?
I also give you the 22nd save by the Google Drive Folder link provided above.

**Comment by KeeyanGhoreshi** [comment] 2024-11-03 05:59
I looked in the drive folder but I cant find the save state for 22.

**Comment by nekmao33** [comment] 2024-11-03 09:17
Oops. It should be good now.

**Comment by KeeyanGhoreshi** [comment] 2024-11-03 17:46
Thanks, it looks like the text when encountering ty and sue is slightly longer than the english version, and the battle doesn't start when it's supposed to.  Easy fix, just add a couple `B` inputs right before the battle.  

Despite it working fine in the english version, the timing on this is unusually tight so I'm actually going to make this change "officially" in the code cause it should have a bit more buffer.

**Comment by nekmao33** [comment] 2024-11-03 18:43
Yep, that works ! Thanks again !👍

**Closed** 2024-11-10 16:13 UTC
