### ISSUE TITLE
Desync at Fantina Gym

### ISSUE THREAD

**Issue by Pulse-kS** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#20] opened 2024-11-13 08:09 UTC
![image](https://github.com/user-attachments/assets/109fcf1e-bc44-4944-954a-3caba87b4e1a)
Gameplay went smoothly for quite a while, however after entering the gym, I noticed a battle prompt had begun with the first gym trainer in fantinas gym, but the script wasn't progressing. I paid it no mind thinking it was intentional, however after coming back to look, I have seen SOUP spinning in place in this spot, and attempting to feed energy powder to a fullHP eevee, indicating a desync

**Comment by KeeyanGhoreshi** [comment] 2024-11-13 22:55
thanks for the report.  If you have the save states, that would be most helpful towards figuring out what happened.  I'm currently doing a full sweep of the code to handle a common issue causing these desyncs, which is lack of proper buffer frames, and my best guess is this falls under that category.

**Comment by KeeyanGhoreshi** [comment] 2024-11-13 23:19
incidentally, I'm on this part of the code now, and I think the problem is actually a bug in the game with the pathing of these specific npcs in fantina's gym.

**Comment by Pulse-kS** [comment] 2024-11-14 05:38
I unfortunately don't have any savestates from before the desync (admittedly this is my first time running bizhawk so I'm not going to be the most helpful) but I've taken one now in case that helps at all [BugReport.txt](https://github.com/user-attachments/files/17743529/BugReport.txt)
I'm planning on restarting a new attempt tonight, I'll try to make regular savestates in case any more issues pop up

**Comment by KeeyanGhoreshi** [comment] 2024-11-14 06:13
That's okay, I've fixed this issue (most likely).  The newest version of the code should save automatically.  If you wait just a little bit I'll have a couple of fixes pushed up that will iron out some of the wrinkles in the earlier scripts.

**Comment by KeeyanGhoreshi** [comment] 2024-11-16 07:51
addressed in #22

**Closed by KeeyanGhoreshi** 2024-11-16 07:51 UTC
